In [2]:
import numpy as np

In [9]:
action_prefs = np.array([5,1,4])
action_prefs

array([5, 1, 4])

In [10]:
np.sum(action_prefs**2)

42

In [13]:
previous_action = 0

In [14]:
action_prefs[previous_action]**2

25

In [17]:
pi = np.zeros(3)
pi

array([0., 0., 0.])

In [18]:
pi[previous_action] = action_prefs[previous_action]**2 / np.sum(action_prefs**2)

In [19]:
pi

array([0.5952381, 0.       , 0.       ])

In [20]:
previous_action = 1
pi[previous_action] = action_prefs[previous_action]**2 / np.sum(action_prefs**2)

In [21]:
pi

array([0.5952381 , 0.02380952, 0.        ])

In [22]:
previous_action = 2
pi[previous_action] = action_prefs[previous_action]**2 / np.sum(action_prefs**2)

In [23]:
pi

array([0.5952381 , 0.02380952, 0.38095238])

In [24]:
np.sum(pi)

1.0

In [ ]:
# update prefs for action taken:
# if baseline:
for action in self._num_of_arms:
    if action == previous_action:
        action_prefs[previous_action] += self._alpha * (reward - self._baseline_avg_reward) * (1 - self._policy[previous_action])
    else:
        action_prefs[action] -= self._alpha * (reward - self._baseline_avg_reward) * self._policy[action])

In [28]:
a = 3
b = 1

In [29]:
a -= b

In [30]:
a

2

In [49]:
pi = np.array([.5,.2,.1,.1,.1])

In [58]:
for _ in range(20):
    b = np.random.choice(5, p=pi)
    print(b)

0
0
0
0
3
0
0
4
1
1
2
0
0
4
3
3
3
1
4
2


In [39]:
b

2